server:
  port: 8080


logging:
  config: classpath:logback-mysql.xml
  level:
    com.crq.boot.controller: debug


#logging:
#  level: {
#     com.crq.boot.controller: trace
#  }

#spring:
#  profiles:
#    active: dev