spring:
  boot:
    admin:
      client:
        url: http://localhost:8081


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
#        暴露endpoints 通过http访问
#        include: health,info,beans,env,customEndpoint

#        禁止Info端点暴露 若两者皆有 则以exclude为准
#        exclude: info